# Generated by Django 4.2.23 on 2025-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('make_year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
