# Generated by Django 4.2.23 on 2025-07-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_car_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=100, unique=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WheelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tread_diameter_new', models.CharField(max_length=50)),
                ('last_shop_issue_size', models.CharField(max_length=50)),
                ('condemning_dia', models.CharField(max_length=50)),
                ('wheel_gauge', models.CharField(max_length=50)),
                ('variation_same_axle', models.CharField(max_length=50)),
                ('variation_same_bogie', models.CharField(max_length=50)),
                ('variation_same_coach', models.CharField(max_length=50)),
                ('wheel_profile', models.CharField(max_length=100)),
                ('intermediate_wwp', models.CharField(max_length=50)),
                ('bearing_seat_diameter', models.CharField(max_length=100)),
                ('roller_bearing_outer_dia', models.CharField(max_length=100)),
                ('roller_bearing_bore_dia', models.CharField(max_length=100)),
                ('roller_bearing_width', models.CharField(max_length=100)),
                ('axle_box_housing_bore_dia', models.CharField(max_length=100)),
                ('wheel_disc_width', models.CharField(max_length=100)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.wheelform')),
            ],
        ),
    ]
