# Generated by Django 4.2.23 on 2025-07-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wheelform_wheelfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheelfield',
            old_name='axle_box_housing_bore_dia',
            new_name='axleBoxHousingBoreDia',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='bearing_seat_diameter',
            new_name='bearingSeatDiameter',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='condemning_dia',
            new_name='condemningDia',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='intermediate_wwp',
            new_name='intermediateWwp',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='last_shop_issue_size',
            new_name='lastShopIssueSize',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='roller_bearing_bore_dia',
            new_name='rollerBearingBoreDia',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='roller_bearing_outer_dia',
            new_name='rollerBearingOuterDia',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='wheel_disc_width',
            new_name='rollerBearingWidth',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='tread_diameter_new',
            new_name='treadDiameterNew',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='variation_same_axle',
            new_name='variationSameAxle',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='variation_same_bogie',
            new_name='variationSameBogie',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='wheel_gauge',
            new_name='variationSameCoach',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='roller_bearing_width',
            new_name='wheelDiscWidth',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='variation_same_coach',
            new_name='wheelGauge',
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='wheel_profile',
            new_name='wheelProfile',
        ),
    ]
