# Generated by Django 4.2.23 on 2025-07-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_axle_box_housing_bore_dia_wheelfield_axleboxhousingboredia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='condittions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='wheelfield',
            old_name='intermediateWwp',
            new_name='intermediateWWP',
        ),
        migrations.CreateModel(
            name='bogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=100, unique=True)),
                ('makerYearBuilt', models.CharField(max_length=100)),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('deficitComponents', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=10)),
                ('dateOfIOH', models.DateField()),
                ('bogieDetailsForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogieDetails', to='api.wheelform')),
            ],
        ),
        migrations.CreateModel(
            name='bogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieFrameCondition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('bolster', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('bolsterSuspensionBracket', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('lowerSpringSeat', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('axleGuide', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('bogieChecksheetForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogieChecksheet', to='api.wheelform')),
            ],
        ),
        migrations.CreateModel(
            name='bmbcChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinderBody', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('pistonTrunnion', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('adjustingTube', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('plungerSpring', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50)),
                ('bmbcChecksheetForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmbcChecksheet', to='api.wheelform')),
            ],
        ),
    ]
