# Generated by Django 4.2.23 on 2025-07-11 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_condittions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bmbcChecksheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinderBody', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
                ('pistonTrunnion', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
                ('adjustingTube', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
                ('plungerSpring', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bogieChecksheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieFrameCondition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
                ('bolster', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
                ('bolsterSuspensionBracket', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
                ('lowerSpringSeat', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
                ('axleGuide', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('condemned', 'Condemned')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bogieDetailsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=50, unique=True)),
                ('makerYearBuilt', models.CharField(max_length=50)),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('deficitComponents', models.CharField(max_length=100)),
                ('dateOfIOH', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='bogieForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=100, unique=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='condittions',
            new_name='CONDTION_CHOICES',
        ),
        migrations.RemoveField(
            model_name='bogiechecksheet',
            name='bogieChecksheetForm',
        ),
        migrations.RemoveField(
            model_name='bogiedetails',
            name='bogieDetailsForm',
        ),
        migrations.DeleteModel(
            name='bmbcChecksheet',
        ),
        migrations.DeleteModel(
            name='bogieChecksheet',
        ),
        migrations.DeleteModel(
            name='bogieDetails',
        ),
        migrations.AddField(
            model_name='bogiedetailsform',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogieDetails', to='api.bogieform'),
        ),
        migrations.AddField(
            model_name='bogiechecksheetform',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogieChecksheet', to='api.bogieform'),
        ),
        migrations.AddField(
            model_name='bmbcchecksheetform',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmbcChecksheet', to='api.bogieform'),
        ),
    ]
