# Generated by Django 4.2.23 on 2025-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bmbcchecksheetform_bogiechecksheetform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CONDTION_CHOICES',
        ),
        migrations.AlterField(
            model_name='bmbcchecksheetform',
            name='adjustingTube',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bmbcchecksheetform',
            name='cylinderBody',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bmbcchecksheetform',
            name='pistonTrunnion',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bmbcchecksheetform',
            name='plungerSpring',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bogiechecksheetform',
            name='axleGuide',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bogiechecksheetform',
            name='bogieFrameCondition',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bogiechecksheetform',
            name='bolster',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bogiechecksheetform',
            name='bolsterSuspensionBracket',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bogiechecksheetform',
            name='lowerSpringSeat',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], max_length=50),
        ),
    ]
