# Generated by Django 4.2.23 on 2025-07-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_condtion_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogiedetailsform',
            name='bogieNo',
            field=models.CharField(max_length=50),
        ),
    ]
